#!/bin/zsh
#filename: bert_base_seq.sub

#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH -A araghu-scale-m
#SBATCH --time=13-12:29:00

module load anaconda/2020.11-py38
conda activate Generation
export HUGGINGFACE_HUB_CACHE=/scratch/gilbreth/amohanpa/cache_for_Generation
export TRANSFORMERS_CACHE=/scratch/gilbreth/amohanpa/cache_for_Generation
export HF_CACHE_HOME=/scratch/gilbreth/amohanpa/cache_for_Generation
export HF_DATASETS_CACHE=/scratch/gilbreth/amohanpa/cache_for_Generation


# python script_brert_base.py
python script_with_return_value.py